name: "Watcharr"
description: "A movie, TV show, and game watchlist tracker"
version: "v4.2.2"
slug: "watcharr"
init: false
arch:
  - amd64
  - aarch64
image: "ghcr.io/sbondco/watcharr"
startup: application
panel_icon: "mdi:movie-roll"
panel_title: "Watcharr"
ingress: true
ingress_port: 3080
map:
  - addon_config:rw # <- Crea y mapea automáticamente /addon_configs/watcharr con permisos de escritura
ports:
  3080/tcp: null # Interfaz web (No requerida externamente si usas Ingress, igual que Glances)
options: {}
schema: {}
environment:
  DB_PATH: "/config/watcharr.db" # <- Al usar addon_config, la ruta interna del contenedor pasa a ser /config
  STORAGE_DIR: "/config"
