name: "Watcharr"
description: "A movie, TV show, and game watchlist tracker"
version: "v4.2.2"
slug: "watcharr"
init: false
arch:
  - amd64
  - aarch64
image: "ghcr.io/sbondco/watcharr"
startup: application
panel_icon: "mdi:movie-roll"
panel_title: "Watcharr"
ingress: true
ingress_port: 3080
map:
  - share:rw
options:
  port: 3080
schema:
  port: port
ports:
  3080/tcp: 3080
environment:
  DB_PATH: "/share/watcharr/watcharr.db"
  STORAGE_DIR: "/share/watcharr"
