name: "qBittorrent"
version: "latest"
slug: "qbittorrent"
description: "qBittorrent torrent client with WebUI, based on the official linuxserver image."
url: "https://github.com/qbittorrent/qBittorrent"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7

image: "lscr.io/linuxserver/qbittorrent"

init: false
startup: "application"
boot: "auto"

ports:
  9090/tcp: 9090
  6881/tcp: 6881
  6881/udp: 6881
ports_description:
  9090/tcp: "qBittorrent WebUI"
  6881/tcp: "Torrenting (TCP)"
  6881/udp: "Torrenting (UDP)"

webui: "http://[HOST]:[PORT:9090]"

ingress: false

map:
  - type: share
    read_only: false
    path: /config
  - type: media
    read_only: false
    path: /downloads

options:
  PUID: 1000
  PGID: 1000
  TZ: "Europe/Madrid"

schema:
  PUID: int
  PGID: int
  TZ: str

environment:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Madrid"
  WEBUI_PORT: "9090"
  TORRENTING_PORT: "6881"

panel_icon: "mdi:cloud-download"
