name: "Navidrome"
description: "Navidrome Music Server - music server compatible with Subsonic/Airsonic"
version: "0.53.3"
slug: "navidrome"
init: false
arch:
  - aarch64
  - amd64
  - armv7
homeassistant: "2023.1.0"
url: "https://www.navidrome.org"

image: "deluan/navidrome"

ports:
  4533/tcp: 4533

ports_description:
  4533/tcp: "Navidrome Web UI y API"

map:
  - share:rw

environment:
  ND_MUSICFOLDER: "/share/music"
  ND_DATAFOLDER: "/data"
  ND_LOGLEVEL: "info"
  ND_PORT: "4533"
  ND_ADDRESS: "0.0.0.0"

options:
  music_folder: "/share/music"
  log_level: "info"

schema:
  music_folder: str
  log_level: list(critical|error|warn|info|debug|trace)
