name: "Homer Dashboard"
version: "latest"
slug: "homer-dashboard"
description: "A simple static homepage for your server, easy to configure via a single yaml file."
url: "https://github.com"

arch:
  - aarch64
  - amd64

image: "b4bz/homer"

init: false
startup: "application"
boot: "auto"

ports:
  8080/tcp: 8080

ports_description:
  8080/tcp: "Homer WebUI (HTTP)"
  
webui: "http://[HOST]:[PORT:8080]"

map:
  - addon_config:rw/www/assets  # <--- MAPEO EXACTO: Conecta directamente la carpeta física con los assets de la app

options:
  TZ: "Europe/Madrid"

schema:
  TZ: str

environment:
  TZ: "Europe/Madrid"
  INIT_ASSETS: "0"  # <--- OBLIGATORIO: Apaga el instalador interactivo de la imagen para que no pregunte "overwrite?" y no aborte
  UID: "0"          # <--- OBLIGATORIO: Ejecuta como root para saltar el bloqueo "Assets directory not writable"
  GID: "0"

panel_icon: "mdi:home-dashboard"
