name: "Scrutiny"
version: "1.0.0"
slug: "scrutiny"
description: "S.M.A.R.T. disk health monitoring, historical metrics, and a web dashboard."
url: "https://github.com/AnalogJ/scrutiny"

arch:
  - aarch64
  - amd64

image: "local/{arch}-scrutiny"

init: false
startup: "application"
boot: "auto"

ports:
  8080/tcp: 8080

ports_description:
  8080/tcp: "Scrutiny WebUI"

webui: "http://[HOST]:[8080]"

watchdog: "http://[HOST]:[8080]/api/health"

map:
  - type: addon_config
    read_only: false

devices:
  - "/dev"

udev: true

full_access: true

options:
  collector_cron_schedule: "0 3 * * *"
  collector_run_startup: true
  debug: false
  timezone: "Europe/Madrid"

schema:
  collector_cron_schedule: str
  collector_run_startup: bool
  debug: bool
  timezone: str

environment:
  TZ: "Europe/Madrid"
  COLLECTOR_CRON_SCHEDULE: "0 3 * * *"
  COLLECTOR_RUN_STARTUP: "true"
  COLLECTOR_RUN_STARTUP_SLEEP: "10"
  DEBUG: "false"

panel_icon: "mdi:harddisk"
panel_title: "Scrutiny"
