name: Kiwix
version: "1.0.0"
slug: kiwix
description: Servidor Kiwix para archivos ZIM almacenados en /share/kiwix
url: "https://github.com/TU_USUARIO/TU_REPOSITORIO"

arch:
  - amd64
  - aarch64
  - armv7

startup: services
init: false

ports:
  8080/tcp: 8080

ports_description:
  8080/tcp: Interfaz web de Kiwix

webui: "http://[HOST]:[8080]"
watchdog: "tcp://[HOST]:[8080]"

map:
  - type: share
    read_only: true

options:
  threads: 4
  verbose: false
  block_external: true

schema:
  threads: int(1,32)
  verbose: bool
  block_external: bool
