name: "Kiwix"
description: "Kiwix - offline .zim server serving files from /share/kiwix"
version: "1.0.1"
slug: "kiwix"
init: false
arch:
  - amd64
  - aarch64
  - armv7
image: "ghcr.io/kiwix/kiwix-serve:latest"
startup: application
panel_icon: "mdi:wikipedia"
ingress: true
ingress_port: 8080
map:
  - share:ro
ports:
  8080/tcp: 8080
options: {}
schema: {}
# ---- FORZAMOS UN SHELL INTERNO PARA MANEJAR EL COMODÍN *.ZIM ----
apparmor: false
privileged:
  - SYS_ADMIN
entrypoint: "/bin/sh"
args:
  - "-c"
  - "exec kiwix-serve --port=8080 /share/kiwix/*.zim"
