name: "Dockhand Local"
description: "Administrador moderno de Docker y Docker Compose integrado en Home Assistant"
version: "v1.0.51" # <- CLAVE: Añadimos la "v" aquí dentro del string de versión
slug: "dockhand_local"
init: false
arch:
  - amd64
  - aarch64
  - armv7
image: "fnsys/dockhand" # <- Queda limpio
startup: application
panel_icon: "mdi:docker"
panel_title: "Dockhand"
ingress: true
privileged:
  - SYS_ADMIN
host_pid: true
map:
  - share:rw
options: {}
schema: {}
