name: "Dockhand Local"
description: "Administrador moderno de Docker y Docker Compose integrado en Home Assistant"
version: "v1.0.51"
slug: "dockhand_local"
init: false
arch:
  - amd64
  - aarch64
  - armv7
image: fnsys/dockhand
startup: application
panel_icon: "mdi:docker"
panel_title: "Dockhand"
ingress: true
ingress_port: 3000
docker_api: true # <- CLAVE: Le dice al Supervisor que monte el archivo /var/run/docker.sock dentro del contenedor
apparmor: false # <- CLAVE: Desactiva las restricciones estrictas de seguridad de HAOS sobre este contenedor
privileged:
  - SYS_ADMIN
host_pid: true
map:
  - share:rw
options:
  port: 3000
schema:
  port: port
ports:
  3000/tcp: 3000
